# Generated by Django 2.2.6 on 2019-11-04 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigIntegerField(default='20191104', primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100, verbose_name='말씀 주제')),
                ('paragraph', models.CharField(max_length=50, verbose_name='말씀 구절')),
                ('guide', models.CharField(max_length=1000, verbose_name='QT 길잡이')),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'QT 게시글',
                'verbose_name_plural': 'QT 게시글',
                'db_table': 'board',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Board')),
            ],
            options={
                'verbose_name': '말씀구절',
                'verbose_name_plural': '말씀구절',
                'db_table': 'word',
                'unique_together': {('board', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Board')),
            ],
            options={
                'verbose_name': '중보기도',
                'verbose_name_plural': '중보기도',
                'db_table': 'prayer',
                'unique_together': {('board', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Contemplation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Board')),
            ],
            options={
                'verbose_name': '개인묵상',
                'verbose_name_plural': '개인묵상',
                'db_table': 'contemplation',
                'unique_together': {('board', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Board')),
            ],
            options={
                'verbose_name': '각주',
                'verbose_name_plural': '각주',
                'db_table': 'annotation',
                'unique_together': {('board', 'order')},
            },
        ),
    ]
